DROP DATABASE IF EXISTS webapp_db;
CREATE DATABASE webapp_db;
USE webapp_db;

DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS videos;

CREATE TABLE accounts (
	userID	INTEGER PRIMARY KEY AUTO_INCREMENT,
	username TINYTEXT NOT NULL UNIQUE,
	password_hash CHAR(128) NOT NULL,
	TotalVideoCount INTEGER NOT NULL DEFAULT 0,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Email VARCHAR(50)
);

CREATE TABLE videos (
	id	INTEGER PRIMARY KEY AUTO_INCREMENT,
	userID	INTEGER NOT NULL,
	videoTitle	TINYTEXT,
	videoURL	TEXT NOT NULL UNIQUE,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT videos_uploader_fk FOREIGN KEY (userID)
		REFERENCES accounts(userID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

GRANT ALL PRIVILEGES ON webapp_db.* TO 'root'@'%'
	IDENTIFIED BY 'toor';
FLUSH PRIVILEGES;

